id     = "ARRAYS"
name   = "Arrays theory"
header = "options/arrays_options.h"

[[option]]
  name       = "arraysOptimizeLinear"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-optimize-linear"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "turn on optimization for linear array terms (see de Moura FMCAD 09 arrays paper)"

[[option]]
  name       = "arraysLazyRIntro1"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-lazy-rintro1"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "turn on optimization to only perform RIntro1 rule lazily (see Jovanovic/Barrett 2012: Being Careful with Theory Combination)"

[[option]]
  name       = "arraysWeakEquivalence"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-weak-equiv"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "use algorithm from Christ/Hoenicke (SMT 2014)"

[[option]]
  name       = "arraysModelBased"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-model-based"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "turn on model-based array solver"

[[option]]
  name       = "arraysEagerIndexSplitting"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-eager-index"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "turn on eager index splitting for generated array lemmas"

[[option]]
  name       = "arraysEagerLemmas"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-eager-lemmas"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "turn on eager lemma generation for arrays"

[[option]]
  name       = "arraysConfig"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-config"
  type       = "int"
  default    = "0"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "set different array option configurations - for developers only"

[[option]]
  name       = "arraysReduceSharing"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-reduce-sharing"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "use model information to reduce size of care graph for arrays"

[[option]]
  name       = "arraysPropagate"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "arrays-prop"
  type       = "int"
  default    = "2"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "propagation effort for arrays: 0 is none, 1 is some, 2 is full"
