id     = "IDL"
name   = "Idl"
header = "options/idl_options.h"

[[option]]
  name       = "idlRewriteEq"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "idl-rewrite-equalities"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "enable rewriting equalities into two inequalities in IDL solver (default is disabled)"
