id     = "STRINGS"
name   = "Strings theory"
header = "options/strings_options.h"

[[option]]
  name       = "stringExp"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-exp"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "experimental features in the theory of strings"

[[option]]
  name       = "stringLB"
  smt_name   = "strings-lb"
  category   = "regular"
  short      = ""
  long       = "strings-lb=N"
  type       = "unsigned"
  default    = "0"
  handler    = ""
  predicates = ["unsignedLessEqual2"]
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "the strategy of LB rule application: 0-lazy, 1-eager, 2-no"

[[option]]
  name       = "stdASCII"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-std-ascii"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = ["unsignedLessEqual2"]
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "the alphabet contains only characters from the standard ASCII or the extended one"

[[option]]
  name       = "stringFMF"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-fmf"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = false
  help       = "the finite model finding used by the theory of strings"

[[option]]
  name       = "stringEager"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-eager"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "strings eager check"

[[option]]
  name       = "stringEIT"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-eit"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "the eager intersection used by the theory of strings"

[[option]]
  name       = "stringOpt1"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-opt1"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "internal option1 for strings: normal form"

[[option]]
  name       = "stringOpt2"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-opt2"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "internal option2 for strings: constant regexp splitting"

[[option]]
  name       = "stringIgnNegMembership"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-inm"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "internal for strings: ignore negative membership constraints (fragment checking is needed, left to users for now)"

[[option]]
  name       = "stringLazyPreproc"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-lazy-pp"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "perform string preprocessing lazily"

[[option]]
  name       = "stringLenGeqZ"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-len-geqz"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "strings length greater than zero lemmas"

[[option]]
  name       = "stringLenNorm"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-len-norm"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "strings length normalization lemma"

[[option]]
  name       = "stringSplitEmp"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-sp-emp"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "strings split on empty string"

[[option]]
  name       = "stringInferSym"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-infer-sym"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "strings split on empty string"

[[option]]
  name       = "stringEagerLen"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-eager-len"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "strings eager length lemmas"

[[option]]
  name       = "stringCheckEntailLen"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-check-entail-len"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "check entailment between length terms to reduce splitting"

[[option]]
  name       = "stringProcessLoop"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-process-loop"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "reduce looping word equations to regular expressions"

[[option]]
  name       = "stringAbortLoop"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-abort-loop"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "abort when a looping word equation is encountered"

[[option]]
  name       = "stringInferAsLemmas"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-infer-as-lemmas"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "always send lemmas out instead of making internal inferences"

[[option]]
  name       = "stringRExplainLemmas"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-rexplain-lemmas"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "regression explanations for string lemmas"

[[option]]
  name       = "stringMinPrefixExplain"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-min-prefix-explain"
  type       = "bool"
  default    = "true"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "minimize explanations for prefix of normal forms in strings"

[[option]]
  name       = "stringGuessModel"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-guess-model"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "use model guessing to avoid string extended function reductions"

[[option]]
  name       = "stringUfReduct"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-uf-reduct"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "use uninterpreted functions when applying extended function reductions"

[[option]]
  name       = "stringBinaryCsp"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-binary-csp"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "use binary search when splitting strings"

[[option]]
  name       = "stringLenPropCsp"
  smt_name   = ""
  category   = "regular"
  short      = ""
  long       = "strings-lprop-csp"
  type       = "bool"
  default    = "false"
  handler    = ""
  predicates = []
  includes   = []
  notifies   = []
  links      = []
  read_only  = true
  help       = "do length propagation based on constant splits"
