name: documentation cleanup
on:
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone docs repo
        run: |
          git config --global user.email "docbot@cvc4"
          git config --global user.name "DocBot"
          git clone https://${{ secrets.TOKEN }}@github.com/nafur/playground.git target/
      
      - name: Remove stale docs
        run: |
          cd target
          for file in `find ./ -maxdepth 1 -name "docs-*"`; do
            mod=`git log -1 HEAD --pretty="%ci" $file`
            touch -d "$mod" $file
          done
          find ./ -maxdepth 1 -name "docs-*" -mtime +7 -exec git rm -r {} +
          git commit -m "Prune docs" || echo "Nothing to prune"

      - name: Squash old commits
        run: |
          first=`git rev-list --max-parents=0 HEAD`
          last=`git rev-list --until=1.month.ago -n1 HEAD`
          git rebase -Xtheirs --onto $first $last
          git log
