name: documentation
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - master
#    paths:
#      - '.ci/**'
#      - 'docs/**'
#      - 'src/api/**'
#  pull_request:
#    branches:
#      - master
#    paths:
#      - '.ci/**'
#      - 'docs/**'
#      - 'src/api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgmp-dev \
            doxygen \
            python3-docutils
          python3 -m pip install \
            setuptools toml \
            sphinxcontrib-bibtex sphinx-tabs sphinx-rtd-theme \
            breathe

      - name: Configure
        run: ./configure.sh debug --docs

      - name: Build
        run: make -j2 docs-gh
        working-directory: build

      - name: Update docs
        run: |
          git config --global user.email "docbot@cvc4"
          git config --global user.name "DocBot"
          if [ "${{ github.event_name }}" == "push" ] ; then
            NAME=$(echo "${GITHUB_REF}" | sed "s,refs/heads/,,")
            echo "Identified branch $NAME"
          elif [ "${{ github.event_name }}" == "pull_request" ] ; then
            NAME=$(echo "${GITHUB_REF}" | sed -E "s,refs/pull/([0-9]+)/merge,\1, ")
            echo "Identified PR #$NAME"
            NAME="pr$NAME"
          else
            return
          fi
          git clone https://${{ secrets.TOKEN }}@github.com/nafur/playground.git target/
          rsync -a --delete build/docs/sphinx-gh/ target/docs-$NAME-${{ github.sha }}
          cd target/
          rm -f docs-$NAME
          ln -s docs-$NAME-${{ github.sha }} docs-$NAME
          git add docs-$NAME docs-$NAME-${{ github.sha }}
          git commit -m "Update docs for $NAME"
          git push
