name: documentation
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - master
#    paths:
#      - '.ci/**'
#      - 'docs/**'
#      - 'src/api/**'
#  pull_request:
#    branches:
#      - master
#    paths:
#      - '.ci/**'
#      - 'docs/**'
#      - 'src/api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgmp-dev \
            doxygen \
            python3-docutils
          python3 -m pip install \
            setuptools toml \
            sphinxcontrib-bibtex sphinx-tabs sphinx-rtd-theme \
            breathe

      - name: Configure
        run: ./configure.sh debug --docs

      - name: Build
        run: make -j2 docs-gh
        working-directory: build

      - name: Update master docs
        if: github.event == 'push' # && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: docs/sphinx-gh
          repository-name: nafur/python-playground #cvc5/cvc5.github.io
          target-folder: docs-master

      - name: Update PR docs
        if: github.event == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: docs/sphinx-gh
          repository-name: nafur/python-playground #cvc5/cvc5.github.io
          target-folder: docs-pr${{ github.event.number }}
