on: [push, pull_request]
name: documentation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgmp-dev \
            flex \
            libfl-dev \
            flexc++
          python3 -m pip install toml setuptools sphinx-tabs

      - name: Configure
        run: ./configure.sh debug --docs

      - name: Build
        run: make -j2 docs
        working-directory: build
