name: Python Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: put windows-latest back in (should also test CVC4 on windows-latest in ci.yml)
        os: [ubuntu-18.04, macos-latest]
          env:
            CIBW_BEFORE_ALL_LINUX=".github/scripts/ubuntu-dependency-installs.sh"
            CIBW_BEFORE_ALL_MACOS=".github/scripts/macos-dependency-installs.sh"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel and Python dependencies
        run: |
          python -m pip install cibuildwheel==1.7.0
          python -m pip install scikit-build Cython ninja toml pytest

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: ./wheelhouse/*.whl

